sudo: required
language: python
python:
- '3.6'
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
   branch: master
